# .github/workflows/ci.yml

name: Run octocov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      -
        name: Run tests with coverage report output
        run: java test ./... -coverprofile=coverage.out
      -
        uses: k1LoW/octocov-action@v0.47.2
